### ISSUE TITLE
Охуенный маппинг.

### ISSUE THREAD

**Issue by AshtonFox** [animusdev/AuroraBlueAdmiralty#16]
Сейчас главная проблема — это инженерный отдел с сингулярным двигателем, в частности, под какое оборудование в нём использованы отсеки, и насколько удобно до него добираться тем, кто в них работает.

Если по порядку, то:
- Цифрами 1.-4. отмечены блоки для хранения скафандров(Suit Storage Unit). И всё бы ничего, но присутствие их и только их огорчает чувства не-человеческих рас. А Аврора — билд весьма толерантный к их (не-человеческих рас) чувствам, как можно судить по бэкстори. Короче, в инженерном отделе наблюдается тотальная нехватка циклеров для скафандров. На практике, это может вылиться в ситуацию, когда ксеноте срочно нужен скафандр, заготовлен он не был, а бежать трэбо аж до ЕВА, роняя кал по разным (экстренным) причинам. Нужно либо заменить один из SSU на циклер(-ы), либо расширить отсек, уже после этого добавив циклер(-ы). Похожая проблема в атмосферном отсеке.

![image](https://user-images.githubusercontent.com/31184078/33043812-bb1b9b74-ce57-11e7-833d-4927e6213b83.png)

- Под цифрами 5.-7. можно наблюдать классическую зависимость СКЛАДА от кнопок в кабинете СЕ. Вроде как должно побуждать игроков заходить за СЕ, но, на самом деле, нахуй оно не надо, и только помешает доступу к реально необходимому оборудованию в критической ситуации(P.A.C.M.A.N.; эмиттеры). Вместо шаттеров (6.-7.) лучше поставить привычные по старой инженерке шлюзы, а кнопку (5.), соответственно, удалить. НЕОБХОДИМО вернуть на склад генераторы щита из той же старой инженерки, как единственное доступное станции средство защиты от метеоров. Имеются в виду те, что огибали, при правильном размещении, весь или почти весь корпус "Исхода" по периметру, и состоят из двух частей: самого генератора и накопителя. 

![image](https://user-images.githubusercontent.com/31184078/33044316-8b6d0046-ce59-11e7-9dbb-04b6a7559a66.png)

- Бонусом мелочи в виде летающих пожарных сигнализаций (8.-10.)
![image](https://user-images.githubusercontent.com/31184078/33044562-664cb3fa-ce5a-11e7-9234-9a33cf45b971.png)

**Comment by Alkoz** [comment]
Етить, я будто бы игровой обзор прочитал. По два предложения на пункт могло хватить.
В любом случае, фиксы уже закоммичены. Приятного <s>вечера</s> утра.
